#!/usr/bin/env expect -f

spawn sh -c $argv

send "5 5\n"

send "1 2 N\n"
send "LMLMLMLMM\n"
expect {
  "1 3 N" { puts PASS }
  timeout { puts FAIL exit }
}

send "3 3 E\n"
send "MMRMMRMRRM\n"
expect {
  "5 1 E" { puts PASS }
  timeout { puts FAIL exit }
}
